### ISSUE TITLE
[CoreML] PT2E requires minimum deployment target as IOS17 and default=None  raises error

### ISSUE THREAD

**Issue by abhinaykukkadapu** [pytorch/executorch#13305]
### 🐛 Describe the bug

Context: https://github.com/pytorch/executorch/pull/13265#discussion_r2267529945

default=None chooses IOS15 but observed an `error: ValueError: No available version for quantize in the coremltools.target.iOS15 opset. Please update the minimum_deployment_target to at least coremltools.target.iOS17`

### Versions

run tests in the PR #13265

**Comment by metascroy** [comment]
This was addressed in the recipe, right @abhinaykukkadapu?

**Comment by abhinaykukkadapu** [comment]
> This was addressed in the recipe, right [@abhinaykukkadapu](https://github.com/abhinaykukkadapu)?

@metascroy  It is still the same: https://github.com/pytorch/executorch/blob/main/backends/apple/coreml/recipes/coreml_recipe_provider.py#L262, is your fix landed ? i briefly followed your PR to address this but i saw it didn't went in at that point of time, is the fix now in?

**Comment by metascroy** [comment]
Oh, I thought this was being addressed in the recipe.  I hadn't planned to address it in the partitioner, but we could turn this issue into a feature request / BE item.
