### ISSUE TITLE
Fix test-arm-backend-delegate

### ISSUE THREAD

**Issue by guangy10** [pytorch/executorch#1569]
#1336 broke `test-arm-backend-delegate` job.

**Comment by Jerry-Ge** [comment]
Hi @guangy10 the `test-arm-backend-delegate` seems is already working from this new job? Could you double check that error? Thanks

**Comment by guangy10** [comment]
> Hi @guangy10 the `test-arm-backend-delegate` seems is already working from this new job? Could you double check that error? Thanks

Hi @Jerry-Ge , from what I can tell here (https://hud.pytorch.org/hud/pytorch/executorch/main, under "Linux" jobs), it's still broken.

**Comment by Jerry-Ge** [comment]
> > Hi @guangy10 the `test-arm-backend-delegate` seems is already working from this new job? Could you double check that error? Thanks
> 
> Hi @Jerry-Ge , from what I can tell here (https://hud.pytorch.org/hud/pytorch/executorch/main, under "Linux" jobs), it's still broken.

Hi @guangy10 , thanks for taking a look. Could that due to the 1701 PR hasn't been merged yet? https://github.com/pytorch/executorch/pull/1701

Since it looks all right from the 1701 PR?

**Comment by guangy10** [comment]
It looks like the job works in #1701 but linter failed. From main I think the linter issue is already fixed. Let me import your PR to latest stable.

**Comment by Jerry-Ge** [comment]
> It looks like the job works in #1701 but linter failed. From main I think the linter issue is already fixed. Let me import your PR to latest stable.

yes, thanks and the PR is also ready to be merged.

**Comment by Jerry-Ge** [comment]
Hi @guangy10, question: 

How could the jobs in #1701 all work. But it still fails at: https://hud.pytorch.org/hud/pytorch/executorch/main ?

**Comment by Jerry-Ge** [comment]
For `test-arm-reference-delegation`, the error is: `/bin/sh: 1: tosa_reference_model: not found`
For `test-arm-backend-delegation`, the error seems is from executorch runtime? https://github.com/pytorch/executorch/actions/runs/7688283587/job/20949317262#step:11:521

**Comment by guangy10** [comment]
> Hi @guangy10, question:
> 
> How could the jobs in #1701 all work. But they still fail at: https://hud.pytorch.org/hud/pytorch/executorch/main ?

Interesting. Before I imported #1701, I saw the job `test-arm-backend-delegate` passed on the PR and the only failure is the linter which has been fixed in main. Let me dig into it.

**Comment by Jerry-Ge** [comment]
> > Hi @guangy10, question:
> > How could the jobs in #1701 all work. But they still fail at: https://hud.pytorch.org/hud/pytorch/executorch/main ?
> 
> Interesting. Before I imported #1701, I saw the job `test-arm-backend-delegate` passed on the PR and the only failure is the linter which has been fixed in main. Let me dig into it.

And they work well on our internal CI. There should be something tiny missing from the CI setup here?

**Comment by Jerry-Ge** [comment]
@robell should found the issue from our side
It's missing the `#include <limits>` in `runtime/core/portable_type/half.h`
He will upstream patch very soon + other fixes.

**Comment by robell** [comment]
there was that and the runner utils were refactored which was a changed after this and hidden behind the compile fail.

Please take a look at #1800
